language: python
cache:
  - pip
  - ccache
  # - yarn
  # - npm
sudo: required
dist: trusty

os:
  - linux

env:
  - JOB=test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # - gcc-5
      # - g++-5
      - git
      - python3
      - python3-pip
      - ccache
      - mongod
      - redis-server

install:
  - sudo pip3 install -r requirements.txt

before_install:

script:
  - [[ "$JOB" == "test" ]] && /bin/bash ./test.sh

notifications:
  email:
    on_success: change
    on_failure: always
